server:
  port: 9001

discovery:
  port: 8761
  hostname: localhost
  username: cheche
  password: cheche

eureka:
  client:
    serviceUrl:
      defaultZone: http://${discovery.username}:${discovery.password}@${discovery.hostname}:${discovery.port}/eureka/

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          thread:
            interruptOnTimeout:false
