package com.cheche365.cheche.core.service.sms

/**
 * Created by yinJianBin on 2017/7/25.
 */
class SmsCodeConstant {
    public static final String TYPE = "type";//类型

    public static final String ORDER_ORDER_NO = '${Order.OrderNo}'
    public static final String ORDER_TRACKING_NO = '${Order.TrackingNo}'
    public static final String ORDER_PREMIUM = '${Order.Premium}'
    public static final String ORDER_AUTO_TAX = '${Order.AutoTax}'
    public static final String ORDER_EFFECTIVE_DATE = '${Order.EffectiveDate}'
    public static final String INSURANCE_COMPANY_NAME = '${InsuranceCompany.Name}'
    public static final String AUTO_LICENSEPLATE_NO = '${Auto.LicensePlateNo}'
    public static final String AUTO_OWNER = '${Auto.Owner}'
    public static final String ADDRESS_MOBILE = '${Address.Mobile}'
    public static final String ORDER_PAY_TIME = '${Order.PayTime}'
    public static final String ORDER_SEND_TIME = '${Order.SendTime}'
    public static final String ORDER_CONFIRM_NO = '${Order.ConfirmNo}'
    public static final String QUOTE_PREMIUM = '${Quote.Premium}'
    public static final String QUOTE_COMPULSORY_PREMIUM = '${Quote.CompulsoryPremium}'
    public static final String QUOTE_COMMERCIAL_PREMIUM = '${Quote.CommercialPremium}'
    public static final String QUOTE_AUTO_TAX = '${Quote.AutoTax}'
    public static final String MARKETING_NAME = '${Marketing.Name}'
    public static final String MARKETING_LANDING_PAGE = '${Marketing.LandingPage}'
    public static final String ORDER_PREMIUM_AMOUNT = '${Order.PremiumAmount}'
    public static final String CUSTOMER_QUOTE_DETAIL = '${CustomerQuoteDetail}'
    public static final String MOBILE = '${Mobile}'
    public static final String VERIFY_CODE = '${VerifyCode}'
    public static final String MINUTE = '${Minute}'
    public static final String M_ORDER_LINK = '${MOrderLink}'
    public static final String M_MY_CENTER_LINK = '${MMyCenterLink}'
    public static final String M_HOME_LINK = '${MHomeLink}'
    public static final String DELIVERY_INSURANCE_DAYS = '${DeliveryInsuranceDays}'
    public static final String GIFT_AMOUNT = '${GiftAmount}'
    public static final String CODE_TYPE = '${CodeType}'
    public static final String CODE = '${Code}'
    public static final String AMOUNT = '${Amount}'
    public static final String M_PAYMENT_LINK = '${MPaymentLink}'
    public static final String NUMBER = '${Number}'
    public static final String THIRD_PARTNER_NAME = '${ThirdPartnerName}'
    public static final String THIRD_PARTNER_MOBILE = '${ThirdPartnerMobile}'
    public static final String PARAM_MOBILE = '${ParamMobile}'
    public static final String SUSPEND_BILL_LINK = '${SusPendBillLink}'
    public static final String RENEWAL_PAY_LINK = '${RenewalPayLink}'
    public static final String USER_NAME = '${User.Name}'
    public static final String ORDER_EXPIRE_DATE = '${Order.ExpireDate}'
    public static final String PLATFORM_NAME = '${Platform.Name}'
    public static final String INTERNAL_USER_NAME = '${InternalUser.Name}'
    public static final String M_ORDER_DETAIL = '${MOrderDetail}'
    public static final String AGENT_MOBILE = '${agentMobile}'
    public static final String AGENT_NAME = '${agentName}'
    public static final String AGENT_LEVEL = '${agentLevel}'
}
